name: hogarya
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  cupertino_icons: ^1.0.8

  firebase_core: ^2.25.5
  firebase_auth: ^4.17.3
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.13.6

  table_calendar: ^3.0.9
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  image_picker: ^1.0.4

  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
  cloudinary_public: ^0.23.1
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.13.0
  fake_cloud_firestore: ^2.5.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LogoHH.png
    - assets/customProfile.svg
    - assets/PhotoBackground.svg
